### ISSUE TITLE
Documation of num labels Argument 

### ISSUE THREAD

**Issue by EricR86** [hoffmangroup/segway#138]
Christopher Neu wrote (from Bitbucket):

In the "Running Segway" part of the Documentation an example run is shown as:

segway --num-labels=4 train test.genomedata traindir

This gives an error. Since "--num-labels" should be behind the "train" command not before.

Thanks

**Comment by k3yavi** [comment]
I can confirm both, the issue and the solution .

**Comment by EricR86** [comment]
Fixed in 82311af
